from typing import Dict, List, Any, Tuple

from .result import MaigretCheckResult
from .types import QueryResultWrapper


class CheckError:
    _type = "Unknown"
    _desc = ""
    _context = None

    def __init__(self, typename, desc="", context=None):
        self._type = typename
        self._desc = desc
        self._context = context  # raw failure context

    def __str__(self):
        base = f"{self._type} error"
        if self._desc:
            base += f": {self._desc}"
        if self._context:
            base += f" | {self._context[:120]}"
        return base

    @property
    def type(self):
        return self._type

    @property
    def desc(self):
        return self._desc

    @property
    def context(self):
        return self._context


# -------------------------
# ERROR DEFINITIONS
# -------------------------

COMMON_ERRORS = {
    "<title>Attention Required! | Cloudflare</title>": CheckError("Captcha", "Cloudflare"),
    "<title>Just a moment</title>": CheckError("Bot protection", "Cloudflare challenge page"),
    "Please stand by, while we are checking your browser": CheckError("Bot protection", "Cloudflare"),
    "<span data-translate=\"checking_browser\">Checking your browser before accessing</span>": CheckError("Bot protection", "Cloudflare"),
    "This website is using a security service to protect itself from online attacks.": CheckError("Access denied", "Cloudflare"),
    "<title>Доступ ограничен</title>": CheckError("Censorship", "Rostelecom"),
    "document.getElementById('validate_form_submit').disabled=true": CheckError("Captcha", "Mail.ru"),
    "Verifying your browser, please wait...<br>DDoS Protection by</font> Blazingfast.io": CheckError("Bot protection", "Blazingfast"),
    "404</h1><p class=\"error-card__description\">Мы&nbsp;не&nbsp;нашли страницу": CheckError("Resolving", "MegaFon 404 page"),
    "Доступ к информационному ресурсу ограничен на основании Федерального закона": CheckError("Censorship", "MGTS"),
    "Incapsula incident ID": CheckError("Bot protection", "Incapsula"),
    "<title>Client Challenge</title>": CheckError("Bot protection", "Anti-bot challenge"),
    "<title>DDoS-Guard</title>": CheckError("Bot protection", "DDoS-Guard"),
    "Сайт заблокирован хостинг-провайдером": CheckError("Site-specific", "Beget block"),
    "Generated by cloudfront (CloudFront)": CheckError("Request blocked", "Cloudflare"),
    "/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page": CheckError("Bot protection", "Cloudflare"),
}

# For tests that reference PROXY_RECOMMENDATION
PROXY_RECOMMENDATION = "Use proxy or bypass service"

ERRORS_TYPES = {
    "Captcha": "Try switching ip address or using cookies",
    "Bot protection": "Try switching IP address or proxy",
    "Access denied": "It's recommended to use --cloudflare-bypass or proxy, e.g. https://vaultproxies.net/maigret",
    "Censorship": "Switch ISP or region",
    "Request timeout": "Increase timeout or retry later",
    "Connecting failure (DNS)": "DNS resolution failed. Check your internet connection or configure --dns-resolver threaded",
    "Webgate unavailable": "cloudflare_bypass is enabled but FlareSolverr solver is not running. Start FlareSolverr with: docker run -p 8191:8191 flaresolverr/flaresolverr. Or set `cloudflare_bypass.enabled` to false",
}


# -------------------------
# CORE FUNCTIONS
# -------------------------

def detect(text: str):
    """
    Detect common error patterns in response text.
    
    Only returns an error if a known error pattern is found.
    Returns None for normal/valid responses.
    """
    if not text:
        return None
    
    # Check for known error patterns only
    for flag, err in COMMON_ERRORS.items():
        if flag in text:
            return err
    
    # No error pattern found - this is a normal response
    return None


def solution_of(err_type: str) -> str:
    return ERRORS_TYPES.get(err_type, "")


# -------------------------
# THRESHOLD LOGIC (FIX FOR is_important ERROR)
# -------------------------

THRESHOLD = 3  # default %

ERROR_THRESHOLDS: Dict[str, float] = {
    "Connecting failure (DNS)": 10,
}


def threshold_for(err_type: str) -> float:
    return ERROR_THRESHOLDS.get(err_type, THRESHOLD)


def is_important(err_data: Dict[str, Any]) -> bool:
    """
    Decide if an error type is significant enough to show in notifications.
    """
    if not err_data:
        return False

    return err_data.get("perc", 0) >= threshold_for(err_data.get("err", ""))


def is_permanent(err_type: str) -> bool:
    return err_type not in [
        "Request timeout",
        "Unknown",
        "Request failed",
        "Connecting failure",
        "Connecting failure (DNS)",
        "Webgate unavailable",
        "HTTP",
        "Proxy",
        "Interrupted",
        "Connection lost",
    ]


# -------------------------
# ERROR ANALYSIS
# -------------------------

def extract_and_group(search_res: QueryResultWrapper) -> List[Dict[str, Any]]:
    errors_counts: Dict[str, int] = {}

    for r in search_res.values():
        if r and isinstance(r, dict) and r.get("status"):
            if not isinstance(r["status"], MaigretCheckResult):
                continue

            err = r["status"].error
            if not err:
                continue

            errors_counts[err.type] = errors_counts.get(err.type, 0) + 1

    total = len(search_res) if search_res else 1

    counts = []
    for err, count in sorted(errors_counts.items(), key=lambda x: x[1], reverse=True):
        counts.append(
            {
                "err": err,
                "count": count,
                "perc": round(count / total, 2) * 100,
            }
        )

    return counts


# -------------------------
# NOTIFICATIONS (FIXED)
# -------------------------

def notify_about_errors(
    search_results: QueryResultWrapper,
    query_notify,
    show_statistics=False,
) -> List[Tuple]:
    results = []

    errs = extract_and_group(search_results)
    was_errs_displayed = False

    for e in errs:
        if not is_important(e):
            continue

        text = f'Too many errors of type "{e["err"]}" ({round(e["perc"], 2)}%)'
        solution = solution_of(e["err"])

        if solution:
            results.append((text, "!", solution.capitalize()))
        else:
            results.append((text, "!"))

        was_errs_displayed = True

    if show_statistics:
        results.append(("Verbose error statistics:", "-"))
        for e in errs:
            results.append((f'{e["err"]}: {round(e["perc"], 2)}%', "!"))

    if was_errs_displayed:
        results.append(
            ("You can see detailed site check errors with --print-errors", "-")
        )

    return results